language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eDL7K+J6YmvJFFuynhVDW3HZfJHUN+ZiQY+PkKbRdxm09xf/Y2q8vxQS5bjnlgM1GUKZz775IEY4GYRapMdrIpJlnb0oRl05/EzHp/St4u1KtF3CI0cci/k7YVsLLnbdnSpyPnTxl7bOOQuRa08NninECQatZSLqrUe6/J37ShWSZeUK/8Ml+H3L+3USJbz/GScwASqtzLKWIyKrVtFutYlJLuoVIfkrOSk5hU+qhTWxtdAii2a1ZCeRdIHTZI+ZriNtSR3OPG1a9fi5y2lVp9rISKMGdTn2y2/VhDYHfe3ckEBZUBINK9ejJjVpS6xKLV2qPT/2ghsbW8WpL1DaxB3V/wjZyL7hL0oVtumzxdCuE4h84yMgNWEsP4WV8ucbver7zbcP8/DBTi9Gr65Q5IGIHJ/XlM5wuh9SwaWnSTDHmJt+raK7bbaW2fp6NW3AvY92+q/3RHCdbwDABQmuHoJNBpDLv4u5unf6nw35EKILkzwawBLZp8VeTUKv5UUjYE7dI14yaDhHOFj3V64phlWNyC2zUlgMTHOAaTf4QVOo8I//9bQg6qYgEFlPmtSC0OooJfsIGDYrdpBoFyv/HzMq3Q+7reMRyNAiqwERItRJVgIeFhkl3QEszIg3ymmucjpAkgDblR9elj3a2S6AqiWGtwmG2Mlw7O8OcKuF6nQ=
  file:
    - 'bail.js'
    - 'bail.min.js'
  on:
    tags: true
